alias: VELUX 100% wenn Sonne stark
description: ""
triggers:
  - trigger: numeric_state
    entity_id:
      - sensor.string_2_w_mod
    above: 300
conditions:
  - condition: state
    entity_id: input_boolean.velux_automatik
    state: "on"
  - condition: numeric_state
    entity_id: sensor.cu401b_g_aussentemperatur
    above: 12
actions:
  - action: input_number.set_value
    metadata: {}
    data:
      value: "100"
    target:
      entity_id: input_number.velux_verdunkelung_soll
mode: single
